osx_image: xcode9
language: objective-c

cache: cocoapods
podfile: Example/Podfile

before_install:
- gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
- pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/InstagramLogin.xcworkspace -scheme InstagramLogin-Example -sdk iphonesimulator11.0 -destination "platform=iOS Simulator,name=iPhone 7 Plus" ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
